alertmanager:
  enabled: false
kube-state-metrics:
  enabled: false
prometheus-pushgateway:
  enabled: false
prometheus-node-exporter:
  enabled: false

server:
  #  baseURL: "/prometheus-server"
  prefixURL: "/prometheus-server"

#additionalScrapeConfigs: |
#  name: additional-scrape-configs
#  key: prometheus-additional.yaml
