apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  namespace: dan-ci-cd
  labels:
    app: nexus
    scope: core
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nexus-pv/
