apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dan-service-logs
  labels:
    strimzi.io/cluster: dan-kafka-cluster
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 900000 # 15 min
    retention.bytes: 1000000000 # 1 Gb
    segment.ms: 900000 # 15 min
    segment.bytes: 1000000000 # 1 Gb
