apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dan-service-logs
  labels:
    strimzi.io/cluster: dan-kafka-cluster
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 7200000 # 2 hours
    retention.bytes: 1000000000 # 1 Gb
    segment.ms: 7200000 # 2 hours
    segment.bytes: 1000000000 # 1 Gb
