apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dan-client-orders
  labels:
    strimzi.io/cluster: dan-kafka-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 900000 # 15 min
    retention.bytes: 1000000000 # 1 Gb
    segment.ms: 900000 # 15 min
    segment.bytes: 1000000000 # 1 Gb

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dan-street-orders
  labels:
    strimzi.io/cluster: dan-kafka-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 900000 # 15 min
    retention.bytes: 1000000000 # 1 Gb
    segment.ms: 900000 # 15 min
    segment.bytes: 1000000000 # 1 Gb

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dan-street-order-acks
  labels:
    strimzi.io/cluster: dan-kafka-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 900000 # 15 min
    retention.bytes: 1000000000 # 1 Gb
    segment.ms: 900000 # 15 min
    segment.bytes: 1000000000 # 1 Gb

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dan-street-order-executions
  labels:
    strimzi.io/cluster: dan-kafka-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 900000 # 15 min
    retention.bytes: 1000000000 # 1 Gb
    segment.ms: 900000 # 15 min
    segment.bytes: 1000000000 # 1 Gb

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: int-fund-messenger-execution
  labels:
    strimzi.io/cluster: dan-kafka-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 900000 # 15 min
    retention.bytes: 1000000000 # 1 Gb
    segment.ms: 900000 # 15 min
    segment.bytes: 1000000000 # 1 Gb
