apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dan-client-orders
  labels:
    strimzi.io/cluster: dan-kafka-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 7200000 # 2 hours
    retention.bytes: 10000000000 # 10 Gb
    segment.ms: 7200000 # 2 hours
    segment.bytes: 1000000000 # 1 Gb

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dan-street-orders
  labels:
    strimzi.io/cluster: dan-kafka-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 7200000 # 2 hours
    retention.bytes: 10000000000 # 10 Gb
    segment.ms: 7200000 # 2 hours
    segment.bytes: 1000000000 # 1 Gb

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dan-street-order-acks
  labels:
    strimzi.io/cluster: dan-kafka-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 7200000 # 2 hours
    retention.bytes: 10000000000 # 10 Gb
    segment.ms: 7200000 # 2 hours
    segment.bytes: 1000000000 # 1 Gb

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dan-street-order-executions
  labels:
    strimzi.io/cluster: dan-kafka-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 7200000 # 2 hours
    retention.bytes: 10000000000 # 10 Gb
    segment.ms: 7200000 # 2 hours
    segment.bytes: 1000000000 # 1 Gb
