apiVersion: v1
kind: PersistentVolume
metadata:
  name: nautica-core-pv
  namespace: dan-ci-cd
  labels:
    app: nautica-core
    scope: core
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nautica-core-pv/
