apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 8.9.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    spec:
      containers:
        - name: kibana
          env:
          resources:
            requests:
              memory: 0.5Gi
              cpu: 50m
            limits:
              memory: 1Gi
              cpu: 500m