apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: dan-ci-cd
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: nexus
      scope: core
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi