datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server

env:
  GF_SERVER_SERVE_FROM_SUB_PATH: 'true'
  GF_SERVER_ROOT_URL: http://k8s.local/grafana
