nameOverride: nexus

#service:
#  enabled: true
#  type: NodePort

ingress:
  enabled: false
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  hostPath: /
  hostRepo: minikube.nexus
    #  tls:
    #    - hosts:
  #        - minikube.nexus
  # tls:
  #   - secretName: nexus-local-tls
#  enabled: true
#  paths: minikube.nexus

persistence:
  enabled: true
  storageSize: 15Gi
  existingClaim: nexus-pvc


nexus:
  env:
    # https://help.sonatype.com/repomanager3/product-information/system-requirements
    - name: INSTALL4J_ADD_VM_PARAMS
      value: |-
        -Xms600M -Xmx1000M
        -XX:MaxDirectMemorySize=1000M
        -XX:+UnlockExperimentalVMOptions
        -XX:+UseCGroupMemoryLimitForHeap
        -Djava.util.prefs.userRoot=/nexus-data/javaprefs
    - name: NEXUS_SECURITY_RANDOMPASSWORD
      value: "true"
    - name: NEXUS_CONTEXT
      value: "nexus"
  resources:
    # https://help.sonatype.com/repomanager3/product-information/system-requirements
    requests:
      cpu: 0.5
      memory: 512Mi
    limits:
      cpu: 4
      memory: 2Gi
  livenessProbe:
    path: "/nexus"
    initialDelaySeconds: 180
  readinessProbe:
    path: "/nexus"
    initialDelaySeconds: 120