apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-docker-cache-pv
  namespace: dan-ci-cd
  labels:
    app: jenkins
    scope: docker-cache
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins-docker-cache-pv/
