yamlApplicationConfig:
  kafka:
    clusters:
      - name: yaml
        bootstrapServers: dan-kafka-cluster-kafka-bootstrap:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false
envs:
  config:
    SERVER_SERVLET_CONTEXT_PATH: "/kafka-ui"