apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 8.12.1
  count: 1
  elasticsearchRef:
    name: elasticsearch
  config:
    server.basePath: "/kibana"
    server.rewriteBasePath: true
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      containers:
        - name: kibana
          readinessProbe:
            httpGet:
              path: /kibana/status
              port: 5601
              scheme: HTTP
          env:
            - name: SERVER_BASEPATH
              value: "/kibana"
            - name: SERVER_REWRITEBASEPATH
              value: "true"
          resources:
            requests:
              memory: 0.5Gi
              cpu: 50m
            limits:
              memory: 1Gi
              cpu: 500m
