apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: dan-ci-cd
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: jenkins
      scope: core
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi